import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // HOME
  container: {
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  apptitle: {
    color: 'black',
    fontWeight: 'bold',
    fontFamily: 'Baskerville',
    fontSize: 65,
    marginBottom: 10,
    textShadowColor: 'white',
    textShadowOffset: {
      width: 2,
      height: 2,
    },
    textShadowRadius: 10,
    backgroundColor: 'transparent',
  },
  image: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  buttonscontainer: {
    alignItems: 'center',
    margin: 20,
  },
  link: {
    height: 50,
    width: 250,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  button: {
    backgroundColor: '#009e0a',
    textAlign: 'center',
    fontWeight: 'bold',
    color: 'white',
    lineHeight: 50,
  },
  resumebutton: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: 'white',
    lineHeight: 50,
    backgroundColor: '#2b6cdb',
  },
  newbutton: {
    backgroundColor: '#009e0a',
    fontWeight: 'bold',
    color: 'white',
    height: 50,
    width: 250,
    textAlign: 'center',
    lineHeight: 50,
    marginBottom: 20,
  },
  finishholelink: {
    backgroundColor: '#009e0a',
    height: 50,
    width: 250,
    marginTop: 10,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  finishholebutton: {
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
    lineHeight: 50,
  },
  quitbutton: {
    backgroundColor: '#cc2828',
    fontWeight: 'bold',
    color: 'white',
    height: 50,
    width: 250,
    textAlign: 'center',
    lineHeight: 50,
    marginBottom: 20,
  },
  picker: {
    height: 750,
    justifyContent: 'center',
    backgroundColor: 'rgba(52, 52, 52, 0.5)',
  },
  pickcourse: {
    marginTop: 20,
    width: 250,
    alignItems: 'flex-start',
    fontWeight: 'bold',
    backgroundColor: 'rgba(52, 52, 52, 0.5)',
    color: 'white',
  },
  statisticsbutton: {
    backgroundColor: 'rgba(52, 52, 52, 0.5)',
    fontWeight: 'bold',
    color: 'white',
    height: 50,
    width: 250,
    textAlign: 'center',
    lineHeight: 50,
    marginBottom: 15,
  },
  // PLAYER SIGNUP
  signupInput: {
    backgroundColor: 'white',
    marginBottom: 10,
    marginLeft: 125,
    height: 50,
    width: 250,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  playerrow: {
    backgroundColor: 'rgba(52, 52, 52, 0.5)',
    flexDirection: 'row',
    margin: 5,
  },
  playername: {
    width: 300,
    height: 50,
    color: 'white',
    fontSize: 20,
    lineHeight: 50,
    textAlign: 'center',
  },
  removebutton: {
    backgroundColor: 'black',
    fontWeight: 'bold',
    color: 'white',
    height: 50,
    width: 50,
    textAlign: 'center',
    lineHeight: 50,
  },
  plusbutton: {
    backgroundColor: '#009e0a',
    fontWeight: 'bold',
    color: 'white',
    height: 50,
    width: 50,
    textAlign: 'center',
    lineHeight: 50,
    marginRight: 5,
  },
  minusbutton: {
    backgroundColor: '#cc2828',
    fontWeight: 'bold',
    color: 'white',
    height: 50,
    width: 50,
    textAlign: 'center',
    lineHeight: 50,
    marginLeft: 5,
    marginRight: 5,
  },
  // GAME
  coursetitle: {
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: -10,
    fontSize: 40,
    alignItems: 'center',
    alignContent: 'center',
    fontFamily: 'Baskerville',
    backgroundColor: 'transparent',
    textShadowColor: 'white',
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    textShadowRadius: 10,
  },
  coursedetailscontainer: {
    flex: 1,
    backgroundColor: 'rgba(52, 52, 52, 0.5)',
    flexDirection: 'row',
    height: 750,
    width: 350,
    marginTop: 20,
  },
  detailscolumn: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    alignContent: 'center',
  },
  courseheader: {
    fontWeight: 'bold',
    color: 'white',
    marginTop: 5,
    fontSize: 20,
    textShadowColor: 'black',
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    textShadowRadius: 10,
  },
  courseyardpar: {
    color: 'white',
    fontSize: 10,
    textShadowColor: 'black',
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    textShadowRadius: 10,
  },
  // player in game display
  playerdisplayrowtop: {
    margin: 5,
  },
  gameplayername: {
    width: 150,
    height: 50,
    backgroundColor: 'rgba(52, 52, 52, 0.5)',
    color: 'white',
    fontSize: 20,
    lineHeight: 50,
    textAlign: 'center',
  },
  scoredisplayrow1: {
    backgroundColor: 'rgba(52, 52, 52, 0.5)',
    flexDirection: 'row',
    flex: 1,
  },
  scoredisplayrow2: {
    flexDirection: 'row',
    flex: 2,
  },
  scoreboxtop: {
    fontWeight: 'bold',
    height: 30,
    width: 30,
    textAlign: 'center',
    lineHeight: 30,
    borderColor: 'black',
    borderWidth: 1,
  },
  scorebox: {
    fontWeight: 'bold',
    height: 45,
    width: 45,
    textAlign: 'center',
    lineHeight: 45,
    borderColor: 'black',
    borderWidth: 1,
  },
  // Stats Pages
  statscontainer: {
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsapptitle: {
    color: 'black',
    fontWeight: 'bold',
    fontFamily: 'Baskerville',
    fontSize: 35,
    marginTop: 20,
    marginBottom: 5,
    height: 50,
    textShadowColor: 'white',
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    textShadowRadius: 10,
    backgroundColor: 'transparent',
  },
  statscoursetitle: {
    fontFamily: 'Baskerville',
    fontWeight: 'bold',
    margin: 15,
    fontSize: 18,
    height: 30,
    lineHeight: 40,
    textShadowColor: 'white',
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    textShadowRadius: 10,
    backgroundColor: 'transparent',
  },
  statsdetailslink: {
    height: 30,
    width: 110,
    backgroundColor: '#2b6cdb',
    marginLeft: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  statsdetailsbutton: {
    marginLeft: 25,
    fontWeight: 'bold',
    height: 30,
    width: 60,
    textAlign: 'center',
    lineHeight: 30,
    color: 'white',
  },
  statsplayercontainer: {
    alignItems: 'flex-start',
    marginLeft: 5,
    marginRight: 5,
  },
  statsname: {
    color: 'white',
    backgroundColor: 'transparent',
    fontWeight: 'bold',
    fontSize: 15,
  },
});
